question_data = [
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                          "question": "Coca-Cola&#039;s original colour was green.", "correct_answer": "False",
                          "incorrect_answers": ["True"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                          "question": "Gumbo is a stew that originated in Louisiana.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                          "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                          "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                          "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                          "question": "The French word to travel is &quot;Travail&quot;", "correct_answer": "False",
                          "incorrect_answers": ["True"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                          "question": "When you cry in space, your tears stick to your face.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                          "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                          "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                          "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
                          "correct_answer": "True", "incorrect_answers": ["False"]}]
